services:
  migrate:
    image: ghcr.io/kukymbr/goose-docker:3.24.1
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: "host=postgres port=${DB_PORT} user=${DB_USER} password=${DB_PASSWORD} dbname=${DB_NAME} sslmode=disable"
      GOOSE_MIGRATION_DIR: /migrations
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
  gateway:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      APP_MODE: ${APP_ENV}
      DB_HOST: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
